CREATE TABLE `taxcode` (
  `taxno` int(11) NOT NULL auto_increment,
  `cityname` varchar(60) NOT NULL,
  `cityno` int(7) unsigned zerofill default NULL,
  `citytax` decimal(5,5) unsigned zerofill default NULL,
  `countyname` varchar(60) default NULL,
  `countyno` int(7) unsigned zerofill default NULL,
  `countytax` decimal(5,5) unsigned zerofill default NULL,
  `spdname` varchar(60) default NULL,
  `spdno` int(7) unsigned zerofill default NULL,
  `spdtax` decimal(5,5) unsigned zerofill default NULL,
  `transitname` varchar(60) default NULL,
  `transitno` int(7) unsigned zerofill default NULL,
  `transittax` decimal(5,5) unsigned zerofill default NULL,
  `totaltax` decimal(5,5) unsigned zerofill default NULL,
  `spd2name` varchar(60) default NULL,
  `spd2no` int(7) unsigned zerofill default NULL,
  `spd2tax` decimal(5,5) unsigned zerofill default NULL,
  `transit2name` varchar(60) default NULL,
  `transit2no` int(7) unsigned zerofill default NULL,
  `transit2tax` decimal(5,5) unsigned zerofill default NULL,
  PRIMARY KEY  (`taxno`),
  KEY `city` (`cityname`),
  KEY `county` (`countyname`),
  KEY `citycounty` (`cityname`,`countyname`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1